### ISSUE TITLE
Теперь Роскомнадзор может заблокировать Гитхаб

### ISSUE THREAD

**Issue by cloudever** [aeroflotsrc/webapp#8]

**Comment by anders0l** [comment]
Или соснуть с причмокиванием

**Comment by fconn** [comment]
Нихуя не будет, скриньте

**Comment by dartraiden** [comment]
Гихаб блокирует доступ из России к репозиториям, запрошенным РКН.

**Comment by dartraiden** [comment]
Кроме того, Гитхаб может заблокировать репозиторий и его форки совсем, если получит от правообладателя DMCA notice.
